export const ADMIN_ROUTES = [
  {
    id: 1,
    title: 'Configurations',
    path: '/configurations',
  },
  {
    id: 2,
    title: 'Add User',
    path: 'registration',
  },
  {
    id: 3,
    title: 'Titles Config',
    path: 'titles',
  },
  {
    id: 4,
    title: 'Deleted Patients',
    path: 'deleted-data',
  },
];

export const ADMIN_TABLE_DATA = {
  doctor: [
    {
      id: 1,
      regDate: '02/02/2024',
      doctorName: 'Lokesh Thakare',
      sex: 'Male',
      age: '26',
      contactNo: '7218509409',
      type: 'Ortho',
      userName: 'lokeshthakare452@gmail.com',
      password: '123',
    }, {
      id: 1,
      regDate: '02/02/2024',
      doctorName: 'Lokesh Thakare',
      sex: 'Male',
      age: '26',
      contactNo: '7218509409',
      type: 'Ortho',
      userName: 'lokeshthakare452@gmail.com',
      password: '123',
    }, {
      id: 1,
      regDate: '02/02/2024',
      doctorName: 'Lokesh Thakare',
      sex: 'Male',
      age: '26',
      contactNo: '7218509409',
      type: 'Ortho',
      userName: 'lokeshthakare452@gmail.com',
      password: '123',
    }, {
      id: 1,
      regDate: '02/02/2024',
      doctorName: 'Lokesh Thakare',
      sex: 'Male',
      age: '26',
      contactNo: '7218509409',
      type: 'Ortho',
      userName: 'lokeshthakare452@gmail.com',
      password: '123',
    }, {
      id: 1,
      regDate: '02/02/2024',
      doctorName: 'Lokesh Thakare',
      sex: 'Male',
      age: '26',
      contactNo: '7218509409',
      type: 'Ortho',
      userName: 'lokeshthakare452@gmail.com',
      password: '123',
    }, {
      id: 1,
      regDate: '02/02/2024',
      doctorName: 'Lokesh Thakare',
      sex: 'Male',
      age: '26',
      contactNo: '7218509409',
      type: 'Ortho',
      userName: 'lokeshthakare452@gmail.com',
      password: '123',
    },
  ],
  staff: [
    {
      id: 1,
      regDate: '02/02/2024',
      doctorName: 'Devesh Thakare',
      sex: 'Male',
      age: '26',
      contactNo: '7218509409',
      type: 'Ortho',
      userName: 'deveshthakare452@gmail.com',
      password: '123',
    },
  ],
  receptionist: [
    {
      id: 1,
      regDate: '02/02/2024',
      doctorName: 'Reception',
      sex: 'Male',
      age: '26',
      contactNo: '7218509409',
      type: 'Ortho',
      userName: 'reception@gmail.com',
      password: '123',
    },
  ],
};
export const ADMIN_TABLE_COLUMNS = {
  doctor: [
    { key: 'id', title: 'ID' },
    { key: 'regDate', title: 'Registration Date' },
    { key: 'doctorName', title: 'Doctor Name' },
    { key: 'sex', title: 'Sex' },
    { key: 'age', title: 'Age' },
    { key: 'contactNo', title: 'Contact No' },
    { key: 'type', title: 'Specialization' },
    { key: 'userName', title: 'Username' },
  ],
  staff: [
    { key: 'id', title: 'ID' },
    { key: 'regDate', title: 'Registration Date' },
    { key: 'doctorName', title: 'Staff Name' },
    { key: 'sex', title: 'Sex' },
    { key: 'age', title: 'Age' },
    { key: 'contactNo', title: 'Contact No' },
    { key: 'type', title: 'Department' },
    { key: 'userName', title: 'Username' },
  ],
  receptionist: [
    { key: 'id', title: 'ID' },
    { key: 'regDate', title: 'Registration Date' },
    { key: 'doctorName', title: 'Receptionist Name' },
    { key: 'sex', title: 'Sex' },
    { key: 'age', title: 'Age' },
    { key: 'contactNo', title: 'Contact No' },
    { key: 'type', title: 'Department' },
    { key: 'userName', title: 'Username' },
  ],
};
